#! /bin/bash
# Script to launch UrbanTerror with Bots
# Author: bebo_sudo
# mailto: bebo.sudo@gmail.com
#

GAME="UrbanTerror"
SCRIPT_NAME="$GAME Bot Launcher"
SCRIPT_VERSION="$SCRIPT_NAME version 0.2"

# get the system arch and fit to the game
ARC=`uname -p`
if [ $ARC = 'i686' ]; then
	ARC=i386
fi

#set here your game folder
FOLDER="$HOME/$GAME"

#this defines the UrbanTerror exec
EXEC="$FOLDER/io$GAME.$ARC"

#change those vars to change texts
TITLE1="UrbanTerror Low Gravity contro il Computer"
TITLE2="Selezione Mappa"
TITLE3="Livello Difficoltà"
TITLE4="Nome Giocatore"
NOMAP="Spiacente, la mappa scelta non è presente nella cartella di sistema."
TEXT1="Scegliere una mappa da un elenco o inserire manualmente il nome della mappa?"
TEXT1_BUTTONNO="Inserire nome manualmente"
TEXT1_BUTTONYES="Scegliere mappa da elenco"
TEXT2="Scegliere il nome della mappa tra quelle consigliate:"
TEXT3="Inserire il nome della mappa da lanciare con i\nbot in bassa gravità (esclusa l'estensione .pk3)."
EXIT_DIALOG="Annullato, chiusura del processo."
MAP_NAME="Nome mappa"
BOT_TEXT="Scegliere il livello di difficoltà:"
LEVEL_BOT="Livello bot"
NOVICE="novizio"
VETERAN="veterano"
TEXT_PLAYER="Inserire il nome del giocatore."
PLAYER_NAME="nome_giocatore"

BOT_LEVEL_SCRIPT="Assegnare un valore da 1 a 5 per i bot alla variabile -b o --bot-level."
NEED_ALL_OPTION="Inserire tutti i parametri!"
UNKNOWN_OPT="Errore da linea di comando: opzione sconosciuta."

ZEN_STATUS=0

function usage {
  echo "usage: $SCRIPT_NAME { --path-to-exec --map --bot-level --name | --help | --version }"
}

function show_help {
cat <<EOF
$(usage)

  -p, --path-to-exec	Set the path to the UrbanTerror exec
  -m, --map		Map name to play with
  -b, --bot-level	Set the bot level
  -n, --name		Player name in the game
  -h, --help		Show this help message
  -v, --version		Script version

If not specified the script assume the launcher is at $EXEC
EOF
}

function show_version {
	cat <<FOE
$SCRIPT_VERSION

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
FOE
}

#function read_map_in_folder {
#	echo $(grep -v '^#' $1 2> /dev/null)
#}

# check if user choose to exit
function answer_checker {
STATUS=$?
if [ "$STATUS" = "1" ]; then
	zenity --info --text="$EXIT_DIALOG"; exit 0
fi
}

# function to collect all zenity questions
function all_zenity {
# get map name | TEXT1 zenity dialog
zenity --question --title="$TITLE1" --text="$TEXT1" \
--cancel-label="$TEXT1_BUTTONNO" --ok-label="$TEXT1_BUTTONYES" --width=400 --height=125

STATUS1=$?
if [ "$STATUS1" = "0" ]; then
	# choose map from a list | TEXT2 zenity dialog
	MAP=`zenity --title="$TITLE2" --text="$TEXT2" --list --radiolist \
	--column="" --column="$MAP_NAME" FALSE "ut4_abbey" FALSE "ut4_algiers" FALSE "ut4_austria" FALSE "ut4_dressingroom" \
	FALSE "ut4_firingrange" FALSE "ut4_mandolin" TRUE "ut4_riyadh" FALSE "ut4_prague" FALSE "ut4_uptown" \
	FALSE "ut4_skeetshoot_2010" --width=350 --height=400`
	# there are a bug on --list option on zenity, so the $? var. doesn't work properly and couldn't exec answer_checker
elif [ "$STATUS1" = "1" ]; then
	# enter map name | TEXT3 zenity dialog 
	MAP=`zenity --entry --title="$TITLE2" \
	--text="$TEXT3" \
	--entry-text "$MAP_NAME"`
	answer_checker
fi

# bot's level
LEVEL=`zenity --title="$TITLE3" --text="$BOT_TEXT" --list --radiolist --column="" --column="$LEVEL_BOT" \
	FALSE "1 ($NOVICE)" FALSE "2" FALSE "3" FALSE "4" TRUE "5 ($VETERAN)" --width=300 --height=270`
	# there are a bug on --list option on zenity, so the $? var. doesn't work properly
if [ "$LEVEL" = "1 ($NOVICE)" ]; then
	LEVEL=1
elif [ "$LEVEL" = "5 ($VETERAN)" ]; then
	LEVEL=5
fi

# player name
NAME=`zenity --entry --title="$TITLE4" --text="$TEXT_PLAYER" --entry-text "$PLAYER_NAME"`

answer_checker

# final zenity check
function zenity_check {
	zenity --question --title="$TITLE1" --text="$ZENITY_CHECK_TEXT" --height=300
  }
}

# urbanterror launcher with bots and some other game vars
function urt_launcher {
$FOLDER/ioUrbanTerror.$ARC +set com_basegame q3ut4 +set fs_basepath /usr/share/q3ut4 \
+set com_hunkMegs 256 +set cl_allowdownload 1 +sv_pure 0 +g_gametype 3 +devmap $MAP \
+g_gravity 70 +exec bot$LEVEL.cfg +name $NAME
}

# check terminal options
if [ -z $1 ]; then
	ZEN_STATUS="1"
	all_zenity
else
	while [ $# -gt 0 ]; do
		case "$1" in
			-p|--path-to-exec)	EXEC=$2 ; shift ; shift ;;
			-m|--map)		MAP=$2	; shift ; shift ;;
			-b|--bot--level)	LEVEL=$2; shift ; shift ;;
			-n|--name)		NAME=$2 ; shift ; shift ;;
			-h|--help)		show_help ; exit $? ;;
			-v|--version)		show_version ; exit $? ;;
			--*|*)
				echo "$(usage)"
				echo "$UNKNOWN_OPT"
				exit 1
			
		esac
	done

	#check if user inserted all vars in
	echo $* |grep "\-p" |grep "\-m"|grep "\-b" |grep "\-n" &> /dev/null
	EXIT=$?
	if [ $EXIT != 0 ]; then
		echo -n "$NEED_ALL_OPTION"
		exit $EXIT
	fi

	# check if bot level is a number from 1 to 5
	case $LEVEL in
		[12345]) LEVEL=$LEVEL ;;
		*)	echo "$BOT_LEVEL_SCRIPT" ;;
	esac

fi

# collect toghether all functions
function all_progs {
if [ $ZEN_STATUS = "1" ]; then
	zenity_check
	answer_checker
fi
urt_launcher
}

ZENITY_CHECK_TEXT="Lanciare il gioco con queste impostazioni?\nPercorso eseguibile: $EXEC\nMappa in cui giocare: \
$MAP\nLivello difficoltà dei bot: $LEVEL\nNome giocatore: $NAME"

#check if map exists already in the urban package
if [ "$MAP" = "ut4_abbey" -o "$MAP" = "ut4_abbeyctf" -o "$MAP" = "ut4_casa" -o "$MAP" = "ut4_company" -o "$MAP" = "ut4_docks" \
	-o "$MAP" = "ut4_herring" -o "$MAP" = "ut4_ambush" -o "$MAP" = "ut4_algiers" -o "$MAP" = "ut4_austria" -o "$MAP" = \
	"ut4_crossing" -o "$MAP" = "ut4_dressingroom" -o "$MAP" = "ut4_eagle" -o "$MAP" = "ut4_elgin" -o "$MAP" = "ut4_firingrange" \
	-o "$MAP" = "ut4_harbortown" -o "$MAP" = "ut4_horror" -o "$MAP" = "ut4_kingdom" -o "$MAP" = "ut4_mandolin" -o "$MAP" = \
	"ut4_maya" -o "$MAP" = "ut4_oildepot" -o "$MAP" = "ut4_ramelle" -o "$MAP" = "ut4_ricochet" -o "$MAP" = "ut4_riyadh" -o \
	"$MAP" = "ut4_prague" -o "$MAP" = "ut4_sanc" -o "$MAP" = "ut4_snoppis" -o "$MAP" = "ut4_suburbs" -o "$MAP" = "ut4_subway" \
	-o "$MAP" = "ut4_swim" -o "$MAP" = "ut4_thingley" -o "$MAP" = "ut4_tombs" -o "$MAP" = "ut4_toxic" -o "$MAP" = "ut4_tunis" \
	-o "$MAP" = "ut4_turnpike" -o "$MAP" = "ut4_uptown" ]; then
	all_progs
else
	# check if map exist in the hidden user folder
	if [ ! -f $FOLDER/q3ut4/$MAP.pk3 ]; then
		if [ $ZEN_STATUS = "1" ]; then
			zenity --info --text="$NOMAP" --timeout=10 ; exit 0
		else
			echo "$NOMAP"; sleep 0.75; echo -n "."; sleep 0.75s; echo -n "."; sleep 0.75s; echo -n "."; sleep 0.75s; exit 0
		fi
	else
		all_progs
	fi
fi

# remove useless game bot library
rm -rf `pwd`/botlib.log
rm -rf $FOLDER/botlib.log

exit 0
# variabile --> \"$FILE\"
